"""Update article column

Revision ID: 2d7d34e553aa
Revises: ed4af445e4f6
Create Date: 2023-07-31 07:27:55.753254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7d34e553aa'
down_revision = 'ed4af445e4f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('article', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('article', sa.Column('dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'dislikes')
    op.drop_column('article', 'likes')
    op.drop_column('article', 'views')
    # ### end Alembic commands ###
